apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
- ../../security
- ../../monitoring

images:
- name: data-pipeline
  newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/data-pipeline
  newTag: ${IMAGE_TAG}

replicas:
- name: data-pipeline
  count: 3

commonLabels:
  environment: prod

patches:
- path: serviceaccount-patch.yaml
- path: deployment-patch.yaml
